version: "3.3"

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile.build
    volumes:
      - ../frontend/:/frontend/dist/
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
  backend:
    build: ../backend/
    env_file: ../backend/.env
    depends_on:
      - db
    # volumes:
    #   - static:/backend_static
